{{ range .Values.volumes }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $.Release.Name }}-{{ .name }}
spec:
  storageClassName: {{ $.Values.storage.class }}
  resources:
    requests:
      storage: {{ $.Values.storage.size }}
  accessModes: {{ $.Values.storage.accessModes }}
  volumeName: {{ $.Release.Name }}-{{ .name }}
{{ end }}
