apiVersion: v2
name: authelia
description: Authelia SSO with OIDC provider
type: application
version: 0.1.0
appVersion: "4.39.0"
dependencies:
  - name: authelia
    version: "0.11.6"
    repository: "https://charts.authelia.com"
    alias: authelia
