---
passwd:
  users:
    - name: core
      ssh_authorized_keys:
        - ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBFvlXc0luAN5p0h3OA9wz5fuUQbXzkGcsyiPqrBpUuAa2dR67coxSt9PmBM4fcaRzcThjkueWqqmjk/FExU0NKg=

systemd:
  units:
    - name: install-opt-dir.service
      enabled: true
      contents: |
        [Unit]
        Description=Install /opt directories
        ConditionPathIsDirectory=!/opt/libexec
        ConditionPathIsDirectory=!/opt/libexec.wd

        [Service]
        Type=oneshot
        ExecStart=/usr/bin/mkdir -p /opt/libexec /opt/libexec.wd

        [Install]
        WantedBy=multi-user.target
    - name: usr-libexec.mount
      enabled: true
      contents: |
        [Unit]
        Description=Allow k8s CNI plugins to be installed
        Before=local-fs.target
        Requires=install-opt-dir.service
        ConditionPathExists=/opt/libexec
        ConditionPathExists=/opt/libexec.wd

        [Mount]
        Type=overlay
        What=overlay
        Where=/usr/libexec
        Options=lowerdir=/usr/libexec,upperdir=/opt/libexec,workdir=/opt/libexec.wd

        [Install]
        WantedBy=local-fs.target
    - name: install-k3s.service
      enabled: true
      contents: |
        [Unit]
        Description=Install k3s
        Requires=usr-libexec.mount
        Wants=network-online.target
        After=network-online.target
        ConditionPathExists=!/opt/bin/k3s

        [Service]
        Type=oneshot
        Environment=INSTALL_K3S_BIN_DIR=/opt/bin INSTALL_K3S_SELINUX_WARN=true INSTALL_K3S_CHANNEL=latest K3S_KUBECONFIG_MODE=644
        ExecStart=/usr/bin/mkdir -p /opt/bin
        ExecStart=/usr/bin/curl -sfSL -o /tmp/k3s.sh https://get.k3s.io
        ExecStart=/usr/bin/chmod +x /tmp/k3s.sh
        ExecStart=/tmp/k3s.sh

        [Install]
        WantedBy=multi-user.target
    - name: mnt-data.mount
      enabled: true
      contents: |
        [Unit]
        Description=Mount data nfs share
        Before=remote-fs.target

        [Mount]
        Type=nfs
        What=192.168.1.100:/mnt/data
        Where=/mnt/data

        [Install]
        WantedBy=remote-fs.target
