---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: namecheap-credentials
spec:
  target:
    name: namecheap-credentials
    creationPolicy: Owner
  data:
    - secretKey: apiUser
      remoteRef:
        key: namecheap
        property: username
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: 1password
    - secretKey: apiKey
      remoteRef:
        key: namecheap
        property: credential
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: 1password
