apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager

resources:
  - external-secret-namecheap-credentials.yaml

helmCharts:
  - releaseName: cert-manager
    name: cert-manager
    namespace: cert-manager
    repo: https://charts.jetstack.io
    version: v1.14.4
    valuesInline:
      installCRDs: true
      global:
        leaderElection:
          namespace: cert-manager
      # see https://github.com/cert-manager/cert-manager/issues/5515#issuecomment-1479054700
      extraArgs:
        - --enable-certificate-owner-ref=true
        - --dns01-recursive-nameservers-only
        - --dns01-recursive-nameservers=8.8.8.8:53,1.1.1.1:53
  - releaseName: letsencrypt-namecheap-issuer
    name: letsencrypt-namecheap-issuer
    namespace: cert-manager
    repo: https://danajp.github.io/cert-manager-webhook-namecheap
    valuesInline:
      email: danajp@gmail.com
      secret: namecheap-credentials
  - releaseName: cert-manager-webhook-namecheap
    name: cert-manager-webhook-namecheap
    namespace: cert-manager
    repo: https://danajp.github.io/cert-manager-webhook-namecheap
