---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: gollum
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: gollum
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gollum
    spec:
#      initContainers:
#        - name: clone
#          image: {{ .Values.gollum.image }}
#          command:
#            - git
#            - clone
#            - {{.Values.repo.url | quote }}
#          workingDir: /wiki
#          volumeMounts:
#            - name: wiki
#              mountPath: /wiki
      containers:
        - name: oauth2-proxy
          image: {{ .Values.oauth2proxy.image }}
          envFrom:
            - secretRef:
                name: oauth2-proxy
          env:
            - name: OAUTH2_PROXY_HTTP_ADDRESS
              value: 0.0.0.0:4180
            - name: OAUTH2_PROXY_UPSTREAM
              value: http://127.0.0.1:4567
            - name: OAUTH2_PROXY_OIDC_ISSUER_URL
              value: https://dev-vfztbfb7mow4uz6e.us.auth0.com
          ports:
            - name: oauth2-proxy
              containerPort: 4180
        - name: main
          image: {{ .Values.gollum.image }}
          {{- if .Values.gollum.args }}
          args: {{ .Values.gollum.args | toJson }}
          {{- end }}
          ports:
            - name: http
              containerPort: 4567
          volumeMounts:
            - name: wiki
              mountPath: /wiki
      volumes:
        - name: wiki
          emptyDir: {}
