---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oauth2-proxy
spec:
  target:
    name: oauth2-proxy
    creationPolicy: Owner
  data:
    - secretKey: OAUTH2_PROXY_CLIENT_ID
      remoteRef:
        key: wiki-oidc
        property: clientid
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: 1password
    - secretKey: OAUTH2_PROXY_CLIENT_SECRET
      remoteRef:
        key: wiki-oidc
        property: clientsecret
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: 1password
    - secretKey: OAUTH2_PROXY_COOKIE_SECRET
      remoteRef:
        key: wiki-oidc
        property: cookiesecret
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: 1password
