---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gollum
spec:
  target:
    name: gollum
    creationPolicy: Owner
  data:
    - secretKey: GITHUB_TOKEN
      remoteRef:
        key: wiki-github-token
        property: credential
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: 1password
