---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gollum
spec:
  target:
    name: gollum
    creationPolicy: Owner
  data:
    - secretKey: GITHUB_TOKEN
      remoteRef:
        key: wiki-github-token
        property: credential
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: 1password
    - secretKey: private-key.pem
      remoteRef:
        key: wiki-github-app-private-key
        property: wiki-danajp-org.2024-12-11.private-key.pem
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: 1password
    - secretKey: GITHUB_APP_ID
      remoteRef:
        key: wiki-github-app
        property: appID
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: 1password
    - secretKey: GITHUB_INSTALLATION_ID
      remoteRef:
        key: wiki-github-app
        property: installationID
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: 1password
