apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: 1password

helmCharts:
  - name: connect
    repo: https://1password.github.io/connect-helm-charts
    version: 1.14.0
    releaseName: 1password-connect
    skipTests: true
