---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authelia
  namespace: {{ .Release.Namespace }}
spec:
  target:
    name: authelia
    creationPolicy: Owner
  data:
    - secretKey: identity_validation.reset_password.jwt.hmac.key
      remoteRef:
        key: authelia-secrets
        property: resetPasswordSecret
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: 1password
    - secretKey: session.encryption.key
      remoteRef:
        key: authelia-secrets
        property: sessionSecret
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: 1password
    - secretKey: storage.encryption.key
      remoteRef:
        key: authelia-secrets
        property: storageEncryptionKey
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: 1password
    - secretKey: identity_providers.oidc.hmac.key
      remoteRef:
        key: authelia-secrets
        property: oidcHmacSecret
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: 1password
