---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authelia-oidc-key
  namespace: {{ .Release.Namespace }}
spec:
  target:
    name: authelia-oidc-key
    creationPolicy: Owner
  data:
    - secretKey: private-key.pem
      remoteRef:
        key: authelia-oidc-private-key
        property: privateKey.pem
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: 1password
