---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authelia-oidc-client-secrets
  namespace: {{ .Release.Namespace }}
spec:
  target:
    name: authelia-oidc-client-secrets
    creationPolicy: Owner
  data:
    - secretKey: gollum-wiki
      remoteRef:
        key: authelia-oidc-client-secrets
        property: gollum-wiki
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: 1password
