---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: 1password-connect
spec:
  destination:
    namespace: 1password
    server: https://kubernetes.default.svc

  project: default

  source:
    path: kustomizations/1password-connect
    repoURL: https://github.com/danajp/home-server.git
    targetRevision: main

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
