---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: plex
spec:
  destination:
    namespace: plex
    server: https://kubernetes.default.svc

  project: default

  source:
    chart: kube-plex
    repoURL: https://ressu.github.io/kube-plex
    targetRevision: 0.3.3
    helm:
      parameters:
        - name: timezone
          value: America/New_York
        - name: kubePlex.enabled
          value: "false"
        - name: ingress.enabled
          value: "true"
        - name: ingress.hosts[0]
          value: plex.home.danajp.org
        - name: ingress.tls[0].hosts[0]
          value: plex.home.danajp.org
        - name: ingress.tls[0].secretName
          value: plex-tls
        - name: ingress.annotations.cert-manager\.io/cluster-issuer
          value: letsencrypt-prod
        - name: service.type
          value: NodePort
        - name: service.nodePort
          value: "32400"
        - name: persistence.data.claimName
          value: plex-data-data
        - name: persistence.config.claimName
          value: plex-data-config

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
