---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: plex-data
spec:
  destination:
    namespace: plex
    server: https://kubernetes.default.svc

  project: default

  source:
    path: helm/charts/plex-data
    repoURL: https://github.com/danajp/home-server.git
    targetRevision: kustomize

    helm:
      parameters:
        - name: hostPath
          value: /mnt/data

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
