---
gollum:
  image: gollumwiki/gollum:6.0.1
  args: [--h1-title, --allow-uploads, dir]
oauth2proxy:
  image: quay.io/oauth2-proxy/oauth2-proxy:v7.7.1
repo:
  url: https://github.com/danajp/personal-wiki
pull:
  cron:
    schedule:
    timezone: America/New_York
    command:
ingress:
  hostname: wiki.home.danajp.org
