apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: plex-data-
namespace: plex

resources:
  - pv.yaml
  - pvc.yaml

configurations:
  - namespace-config.yaml
  - name-prefix-config.yaml
