---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 800Gi
  claimRef:
    name: data
  hostPath:
    path: /mnt/data/media
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: config
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 800Gi
  claimRef:
    name: config
  hostPath:
    path: /mnt/data/plex
