---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
spec:
  storageClassName: local-path
  resources:
    requests:
      storage: 800Gi
  accessModes:
    - ReadWriteMany
  volumeName: data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config
spec:
  storageClassName: local-path
  resources:
    requests:
      storage: 800Gi
  accessModes:
    - ReadWriteMany
  volumeName: config
