---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: plex-data
  namespace: {{ .Release.Namespace }}
spec:
  destination:
    namespace: plex
    server: {{ .Values.server }}

  project: {{ .Values.project }}

  source:
    path: helm/charts/plex-data
    repoURL: https://github.com/danajp/home-server.git
    targetRevision: master

    helm:
      parameters:
        - name: hostPath
          value: /mnt/data

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
