---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ingress-nginx

helmCharts:
  - name: ingress-nginx
    repo: https://kubernetes.github.io/ingress-nginx
    version: 4.10.0
    releaseName: ingress-nginx
    skipTests: true

patches:
  - target:
      kind: IngressClass
      name: nginx
    patch: |
      - op: add
        path: /metadata/annotations/ingressclass.kubernetes.io~1is-default-class
        value: "true"
