---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  destination:
    namespace:  {{ .Release.Namespace }}
    server: https://kubernetes.default.svc
  project: {{ .Values.project }}
  source:
    path: applications
    repoURL: https://github.com/{{ .Values.repo.owner }}/{{ .Values.repo.name }}.git
    targetRevision: {{ .Values.repo.targetRevision }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
