apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: 1password
spec:
  provider:
    onepassword:
      connectHost: http://onepassword-connect.1password.svc.cluster.local:8080
      vaults:
        home-server: 1
      auth:
        secretRef:
          connectTokenSecretRef:
            namespace: external-secrets
            name: 1password-connect-token
            key: token
