kind: ExternalSecret
apiVersion: external-secrets.io/v1beta1
metadata:
  name: repo-home-server
spec:
  secretStoreRef:
    name: 1password
    kind: ClusterSecretStore
  target:
    name: repo-home-server
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        type: git
        project: default
        name: home-server
        url: https://github.com/danajp/home-server
        username: danajp
        password: "{{ .apiKey }}"
  data:
    - secretKey: apiKey
      remoteRef:
        key: github.com
        property: argo-cd-pat
