kind: ExternalSecret
apiVersion: external-secrets.io/v1beta1
metadata:
  name: repo-creds-github
spec:
  secretStoreRef:
    name: 1password
    kind: ClusterSecretStore
  target:
    name: repo-creds-github
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repo-creds
      data:
        type: git
        project: default
        name: github-danajp
        url: https://github.com/danajp/home-server
        githubAppID: "{{ .appID }}"
        githubAppInstallationID: "{{ .installationID }}"
        githubAppPrivateKey: "{{ .privateKey }}"
  data:
    - secretKey: appID
      remoteRef:
        key: argo-cd-github-app
        property: appID
    - secretKey: installationID
      remoteRef:
        key: argo-cd-github-app
        property: installationID
    - secretKey: privateKey
      remoteRef:
        key: argo-cd-github-app-private-key

