---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: minecraft
  template:
    metadata:
      labels:
        app.kubernetes.io/name: minecraft
    spec:
      containers:
        - name: main
          image: itzg/minecraft-server
          tty: true
          stdin: true
          ports:
            - name: minecraft
              containerPort: 25565
          env:
            - name: EULA
              value: "TRUE"
