---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: minecraft
  template:
    metadata:
      labels:
        app.kubernetes.io/name: minecraft
    spec:
      containers:
        - name: main
          image: itzg/minecraft-bedrock-server
          tty: true
          stdin: true
          ports:
            - name: minecraft
              containerPort: 19132
              protocol: UDP
          env:
            - name: EULA
              value: "TRUE"
            - name: SERVER_PORT
              value: "udp://0.0.0.0:19132"
