---
apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: minecraft
  ports:
    - name: minecraft
      port: 19132
      protocol: UDP
      targetPort: minecraft
