---
apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: minecraft
  ports:
    - name: minecraft
      port: 19132
      nodePort: 32132
      protocol: UDP
